import json
import os
import re
from typing import Any

import requests


ALLOWED_ACHIEVEMENTS = {
    'New Job', 'Internship', 'Promotion', 'Certification', 'Project Completed', 'Hackathon',
    'Competition', 'Academic Achievement', 'Learning Milestone', 'Career Milestone',
    'Personal Achievement', 'Team Achievement', 'Other'
}

ALLOWED_MOODS = {
    'Excited', 'Happy', 'Grateful', 'Confident', 'Motivated', 'Inspirational', 'Humble',
    'Professional', 'Reflective', 'Proud'
}

ALLOWED_WORD_LENGTHS = {'Short', 'Medium', 'Long', 'Custom'}
ALLOWED_TONES = {
    'Professional', 'Friendly', 'Inspirational', 'Storytelling', 'Emotional', 'Confident',
    'Humble', 'Thought Leadership', 'Casual Professional'
}
ALLOWED_AUDIENCES = {
    'Recruiters', 'Developers', 'Students', 'Entrepreneurs', 'AI/ML Professionals',
    'General LinkedIn Audience', 'Hiring Managers', 'Tech Community'
}
ALLOWED_STYLES = {
    'Storytelling', 'Achievement Announcement', 'Lessons Learned', 'Career Journey',
    'Technical Explanation', 'Problem → Solution', 'Before → After', 'Personal Experience',
    'Motivational', 'Thought Leadership'
}


def validate_generation_payload(payload: dict):
    if not isinstance(payload, dict):
        raise ValueError('Invalid request payload.')

    required_fields = ['topic', 'achievement', 'mood', 'feeling', 'word_length', 'tone', 'audience', 'style']
    for field in required_fields:
        if field not in payload or payload.get(field) is None or str(payload.get(field)).strip() == '':
            raise ValueError(f'{field} is required.')

    topic = str(payload['topic']).strip()
    achievement = str(payload['achievement']).strip()
    mood = str(payload['mood']).strip()
    feeling = str(payload['feeling']).strip()
    word_length = str(payload['word_length']).strip()
    tone = str(payload['tone']).strip()
    audience = str(payload['audience']).strip()
    style = str(payload['style']).strip()

    if len(topic) < 3:
        raise ValueError('Topic must be at least 3 characters long.')
    if len(feeling) < 10:
        raise ValueError('Feeling must be at least 10 characters long.')
    if achievement not in ALLOWED_ACHIEVEMENTS:
        raise ValueError('Invalid achievement type.')
    if mood not in ALLOWED_MOODS:
        raise ValueError('Invalid mood selection.')
    if word_length not in ALLOWED_WORD_LENGTHS:
        raise ValueError('Invalid word length selection.')
    if tone not in ALLOWED_TONES:
        raise ValueError('Invalid tone selection.')
    if audience not in ALLOWED_AUDIENCES:
        raise ValueError('Invalid audience selection.')
    if style not in ALLOWED_STYLES:
        raise ValueError('Invalid style selection.')

    return {
        'topic': topic,
        'achievement': achievement,
        'mood': mood,
        'feeling': feeling,
        'word_length': word_length,
        'tone': tone,
        'audience': audience,
        'style': style,
    }


def get_word_target(word_length: str):
    mapping = {
        'Short': (50, 100),
        'Medium': (100, 200),
        'Long': (200, 300),
        'Custom': (100, 220),
    }
    return mapping.get(word_length, (100, 200))


def build_prompt(data: dict):
    target_min, target_max = get_word_target(data['word_length'])
    return f"""
You are writing a polished, authentic LinkedIn post for a professional audience.

Requirements:
- Topic: {data['topic']}
- Achievement: {data['achievement']}
- Mood: {data['mood']}
- Feeling: {data['feeling']}
- Tone: {data['tone']}
- Audience: {data['audience']}
- Style: {data['style']}
- Target length: {target_min}-{target_max} words

Write a high-quality LinkedIn post that:
- opens with a strong hook
- feels authentic and credible
- uses clear, concise paragraphs
- includes natural LinkedIn storytelling flow
- emphasizes the user’s real experience without inventing details
- includes a meaningful takeaway and conclusion
- avoids emojis, exaggerated claims, fake statistics, fake companies, fake certifications, or fabricated experiences
- does not mention AI or that the content was generated by AI
- stays within the requested word length
- uses relevant hashtags at the end (3-5)

Return valid JSON only in this exact structure:
{
  "content": "post text",
  "hashtags": ["#tag1", "#tag2", "#tag3"],
  "word_count": 180
}

The content should read naturally on LinkedIn, use short paragraphs, and feel professional but human.
""".strip()


def sanitize_text(value: str) -> str:
    if not isinstance(value, str):
        return ''
    cleaned = value.replace('\r', '\n').strip()
    cleaned = re.sub(r'\n{3,}', '\n\n', cleaned)
    cleaned = re.sub(r'\s{2,}', ' ', cleaned)
    return cleaned.strip()


def get_hashtags(content: str):
    hashtags = re.findall(r'#\w+', content)
    if len(hashtags) >= 3:
        return list(dict.fromkeys(hashtags))[:5]
    fallback = ['#CareerGrowth', '#ProfessionalDevelopment', '#Leadership', '#Learning', '#LinkedIn']
    return fallback[:5]


def parse_ai_response(raw_response: Any):
    if raw_response is None:
        raise ValueError('AI response is empty.')

    if isinstance(raw_response, dict):
        payload = raw_response
    else:
        if isinstance(raw_response, str):
            text = raw_response.strip()
            if text.startswith('```'):
                text = re.sub(r'^```(?:json)?\s*', '', text)
                text = re.sub(r'\s*```\s*$', '', text)
            try:
                payload = json.loads(text)
            except json.JSONDecodeError as exc:
                raise ValueError('AI response was not valid JSON.') from exc
        else:
            raise ValueError('AI response format is invalid.')

    if not isinstance(payload, dict):
        raise ValueError('AI response payload is invalid.')

    content = sanitize_text(payload.get('content', ''))
    hashtags = payload.get('hashtags') or get_hashtags(content)
    if not isinstance(hashtags, list):
        hashtags = get_hashtags(content)
    hashtags = [str(tag).strip() for tag in hashtags if str(tag).strip()][:5]
    if not hashtags:
        hashtags = ['#CareerGrowth', '#ProfessionalDevelopment', '#LinkedIn']

    if not content or len(content) < 40:
        raise ValueError('Generated post content is too short.')

    word_count = payload.get('word_count')
    if not isinstance(word_count, int):
        try:
            word_count = len(re.findall(r'\b\w+\b', content))
        except Exception:
            word_count = 0

    if word_count <= 0:
        word_count = len(re.findall(r'\b\w+\b', content))

    return {
        'content': content,
        'hashtags': hashtags,
        'word_count': max(word_count, 1),
    }


def build_provider_request(data: dict):
    api_key = os.getenv('AI_API_KEY')
    provider = os.getenv('AI_PROVIDER', 'openai').lower()
    endpoint = os.getenv('AI_ENDPOINT', '').strip()
    model = os.getenv('AI_MODEL', 'gpt-4o-mini')

    if not api_key:
        raise RuntimeError('AI service is not configured.')

    if provider == 'openai' and not endpoint:
        endpoint = 'https://api.openai.com/v1/chat/completions'

    return {
        'api_key': api_key,
        'provider': provider,
        'endpoint': endpoint,
        'model': model,
        'prompt': build_prompt(data),
    }


def build_local_post(data: dict):
    topic = data['topic']
    achievement = data['achievement']
    mood = data['mood']
    feeling = data['feeling']
    tone = data['tone']
    audience = data['audience']
    style = data['style']

    intro = (
        f"I’m excited to share a milestone in {topic} that has shaped my journey and reinforced what really matters."
        if tone != 'Storytelling'
        else f"This moment in {topic} reminded me that progress is rarely linear, and that the hardest part is often simply starting."
    )

    body = (
        f"{achievement} has been a meaningful step for me, and it comes with a lot of gratitude. "
        f"{feeling} That experience reminded me that growth is not just about outcomes, but about learning, persistence, and the people who support the process. "
        f"For {audience}, I want to highlight that success is built through consistent effort, curiosity, and the courage to keep moving forward."
    )

    closing = (
        f"I’m grateful for the opportunity to keep learning and building in this space. "
        f"If you’re working on something meaningful right now, keep going — the process is part of the progress."
    )

    content = f"{intro}\n\n{body}\n\n{closing}"
    hashtags = [
        '#CareerGrowth',
        '#ProfessionalDevelopment',
        '#Leadership',
        '#Learning',
        '#LinkedIn'
    ]

    return {
        'content': content,
        'hashtags': hashtags,
        'word_count': len(re.findall(r'\b\w+\b', content)),
    }


def call_ai_provider(data: dict):
    if not os.getenv('AI_API_KEY'):
        return build_local_post(data)

    request_info = build_provider_request(data)
    headers = {
        'Authorization': f"Bearer {request_info['api_key']}",
        'Content-Type': 'application/json',
    }
    payload = {
        'model': request_info['model'],
        'messages': [
            {'role': 'system', 'content': 'You write polished LinkedIn posts for professionals.'},
            {'role': 'user', 'content': request_info['prompt']},
        ],
        'temperature': 0.7,
        'max_tokens': 400,
    }

    try:
        response = requests.post(request_info['endpoint'], headers=headers, json=payload, timeout=30)
        if response.status_code == 429:
            raise RuntimeError('AI service is rate limited.')
        if response.status_code >= 400:
            raise RuntimeError('AI service is unavailable.')
        decoded = response.json()
        result = decoded.get('choices', [{}])[0].get('message', {}).get('content', '')
        return result
    except requests.exceptions.Timeout as exc:
        raise RuntimeError('AI service timed out.') from exc
    except requests.exceptions.RequestException as exc:
        raise RuntimeError('AI service is unavailable.') from exc


def generate_post(data: dict):
    validated = validate_generation_payload(data)
    ai_response = call_ai_provider(validated)
    if isinstance(ai_response, dict):
        return ai_response
    structured = parse_ai_response(ai_response)
    return structured


def generate_variations(data: dict):
    base = validate_generation_payload(data)
    variations = []
    for tone in ['Professional', 'Storytelling', 'Inspirational']:
        candidate = {**base, 'tone': tone}
        try:
            result = generate_post(candidate)
            variations.append({
                'tone': tone,
                **result,
            })
        except Exception:
            variations.append({
                'tone': tone,
                'content': f"I’m excited to share this milestone in {base['topic']} and the lessons it taught me along the way.",
                'hashtags': ['#CareerGrowth', '#Leadership', '#ProfessionalDevelopment'],
                'word_count': 34,
            })
    return variations
